language: cpp
os: linux
dist: focal

jobs:
  include:
    - name: "AMD64"
      env:
      - DOCKER_ARCH=linux/amd64
    - name: "ARMv7"
      env:
      - DOCKER_ARCH=linux/arm/v7
    - name: "ARM64"
      env:
      - DOCKER_ARCH=linux/arm64

before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start

install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
- docker buildx create --name builder --use

script:
- docker buildx build --platform "$DOCKER_ARCH" -t "$DOCKER_TAG" --push .